// AUTO-GENERATED by scripts/sync_blueprints_ts.py from kevin/config.py
// Do not edit manually — run: python scripts/sync_blueprints_ts.py


export const VALID_BLUEPRINTS: ReadonlySet<string> = new Set([
  "bp_architecture_blueprint_design.1.0.0",
  "bp_ba_requirement_analysis.1.0.0",
  "bp_backend_coding_tdd_automation.1.0.0",
  "bp_code_review.1.0.0",
  "bp_coding_task.1.0.0",
  "bp_deployment_monitoring_automation.1.0.0",
  "bp_frontend_feature_ui_design.1.0.0",
  "bp_function_implementation_fip_blueprint.1.0.0",
  "bp_test_advanced.1.0.0",
  "bp_test_e2e.1.0.0",
  "bp_test_environment_setup.1.0.0",
  "bp_test_feature_comprehensive_testing.1.0.0",
  "bp_test_frontend.1.0.0",
  "bp_test_integration.1.0.0",
  "bp_test_report_signoff.1.0.0",
  "bp_test_strategy_design.1.0.0",
  "bp_test_unit.1.0.0",
]);

export const AVAILABLE_BLUEPRINTS: ReadonlyArray<string> = [...VALID_BLUEPRINTS].sort();
