"""Execute Blueprint blocks via pluggable runners + validators.

Runners:
  - claude_cli: invoke `claude -p <prompt> --cwd <dir>`
  - shell: run a shell command
  - api_call: HTTP request (urllib, no extra deps)

Validators (run after block execution):
  - git_diff_check: ensure git has uncommitted/new changes
  - command: run a shell command, expect exit 0
  - file_exists: check a file/glob exists
"""

from __future__ import annotations

import glob as glob_mod
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.request import Request, urlopen

# Seconds of silence before the heartbeat watchdog kills a subprocess.
# Claude CLI can think for a while, so this needs to be generous.
HEARTBEAT_TIMEOUT_SECONDS = 120

from kevin.blueprint_loader import Block, Validator
from kevin.prompt_template import render


@dataclass
class BlockResult:
    """Result of executing a single block."""

    block_id: str
    success: bool
    exit_code: int | None = None
    stdout: str = ""
    stderr: str = ""
    prompt: str = ""
    validator_results: list[dict[str, Any]] | None = None


# ---------------------------------------------------------------------------
# Runner dispatch
# ---------------------------------------------------------------------------

def run_block(
    block: Block,
    variables: dict[str, str],
    *,
    dry_run: bool = False,
) -> BlockResult:
    """Execute a block using the appropriate runner, then validate."""
    runner = block.runner or "claude_cli"

    if dry_run:
        return BlockResult(
            block_id=block.block_id,
            success=True,
            stdout=f"[dry-run] Would execute {runner} block {block.block_id}",
        )

    # Run pre_check for idempotency (e.g. git checkout . && git clean -fd)
    pre_check_result = _run_pre_check(block, variables)
    if pre_check_result is not None:
        return pre_check_result

    runner_fn = RUNNERS.get(runner)
    if runner_fn is None:
        return BlockResult(
            block_id=block.block_id,
            success=False,
            stderr=f"Unknown runner: {runner}",
        )

    result = runner_fn(block, variables)

    # Run validators if block execution succeeded
    if result.success and block.validators:
        cwd = _resolve_cwd(block.runner_config, variables)
        v_results = _run_validators(block.validators, variables, cwd)
        result.validator_results = v_results
        if any(not v["passed"] for v in v_results):
            result.success = False
            failed = [v for v in v_results if not v["passed"]]
            result.stderr += f"\nValidator failures: {failed}"

    return result


# ---------------------------------------------------------------------------
# Runner implementations
# ---------------------------------------------------------------------------

def _run_claude_cli(block: Block, variables: dict[str, str]) -> BlockResult:
    """Execute a block via `claude -p <prompt> --cwd <dir>`.

    Supports runner_config.context_filter: a list of gitignore-style patterns
    to exclude from Claude CLI's context (e.g. ["node_modules", "dist", "*.min.js"]).
    When provided, a temporary .claudeignore file is written to the cwd before
    execution and cleaned up afterward.
    """
    prompt = render(block.prompt_template, variables)
    cwd = _resolve_cwd(block.runner_config, variables)
    model = block.runner_config.get("model", "")
    context_filter: list[str] = block.runner_config.get("context_filter", [])

    cmd = ["claude", "-p", prompt, "--cwd", str(cwd)]
    if model:
        cmd.extend(["--model", model])

    # Write temporary .claudeignore for context budget management
    claudeignore_path = cwd / ".claudeignore"
    created_claudeignore = False
    if context_filter and not claudeignore_path.exists():
        claudeignore_path.write_text(
            "# Auto-generated by Kevin (context budget management)\n"
            + "\n".join(context_filter)
            + "\n",
            encoding="utf-8",
        )
        created_claudeignore = True

    try:
        result = _subprocess_run(block.block_id, cmd, cwd=cwd, timeout=block.timeout)
        result.prompt = prompt
        return result
    finally:
        if created_claudeignore and claudeignore_path.exists():
            claudeignore_path.unlink()


def _run_shell(block: Block, variables: dict[str, str]) -> BlockResult:
    """Execute a shell command from runner_config.command."""
    command = block.runner_config.get("command", "")
    if not command:
        return BlockResult(
            block_id=block.block_id,
            success=False,
            stderr="shell runner requires runner_config.command",
        )

    command = render(command, variables)
    cwd = _resolve_cwd(block.runner_config, variables)

    return _subprocess_run(
        block.block_id,
        ["bash", "-c", command],
        cwd=cwd,
        timeout=block.timeout,
    )


def _run_api_call(block: Block, variables: dict[str, str]) -> BlockResult:
    """Execute an HTTP API call (no extra deps — uses urllib)."""
    config = block.runner_config
    method = config.get("method", "GET")
    url = render(config.get("url", ""), variables)
    headers = {k: render(str(v), variables) for k, v in config.get("headers", {}).items()}
    body = config.get("body")

    if not url:
        return BlockResult(
            block_id=block.block_id,
            success=False,
            stderr="api_call runner requires runner_config.url",
        )

    try:
        import json
        data = json.dumps(body).encode() if body else None
        req = Request(url, data=data, headers=headers, method=method)
        with urlopen(req, timeout=block.timeout) as resp:
            resp_body = resp.read().decode()
            return BlockResult(
                block_id=block.block_id,
                success=resp.status < 400,
                exit_code=resp.status,
                stdout=resp_body,
            )
    except Exception as exc:
        return BlockResult(
            block_id=block.block_id,
            success=False,
            stderr=str(exc),
        )


RUNNERS = {
    "claude_cli": _run_claude_cli,
    "shell": _run_shell,
    "api_call": _run_api_call,
}


# ---------------------------------------------------------------------------
# Pre-check (idempotency reset)
# ---------------------------------------------------------------------------

def _run_pre_check(block: Block, variables: dict[str, str]) -> BlockResult | None:
    """Run a block's pre_check command if defined.

    Returns None on success (or if no pre_check), BlockResult on failure.
    The pre_check is a shell command that resets the workspace to a clean state
    before (re-)executing the block — critical for resume/retry idempotency.
    """
    if not block.pre_check:
        return None

    command = render(block.pre_check, variables)
    cwd = _resolve_cwd(block.runner_config, variables)

    result = subprocess.run(
        ["bash", "-c", command],
        capture_output=True,
        text=True,
        cwd=str(cwd),
        timeout=30,
    )

    if result.returncode != 0:
        return BlockResult(
            block_id=block.block_id,
            success=False,
            exit_code=result.returncode,
            stderr=f"pre_check failed: {result.stderr}",
        )

    return None


# ---------------------------------------------------------------------------
# Validator implementations
# ---------------------------------------------------------------------------

def _run_validators(
    validators: list[Validator],
    variables: dict[str, str],
    cwd: Path,
) -> list[dict[str, Any]]:
    """Run all validators and return results."""
    results: list[dict[str, Any]] = []
    for v in validators:
        fn = VALIDATORS.get(v.type)
        if fn is None:
            results.append({"type": v.type, "passed": False, "error": f"Unknown validator: {v.type}"})
            continue
        results.append(fn(v, variables, cwd))
    return results


def _validate_git_diff(v: Validator, variables: dict[str, str], cwd: Path) -> dict[str, Any]:
    """Check that git has file changes."""
    min_files = v.params.get("min_files_changed", 1)
    result = subprocess.run(
        ["git", "diff", "--stat", "HEAD"],
        capture_output=True, text=True, cwd=str(cwd), timeout=10,
    )
    # Count changed files from diff --stat (last line is summary)
    lines = [line for line in result.stdout.strip().split("\n") if line.strip()]
    # Also check staged + untracked
    status = subprocess.run(
        ["git", "status", "--porcelain"],
        capture_output=True, text=True, cwd=str(cwd), timeout=10,
    )
    changed_files = len([l for l in status.stdout.strip().split("\n") if l.strip()])
    passed = changed_files >= min_files
    return {
        "type": "git_diff_check",
        "passed": passed,
        "files_changed": changed_files,
        "expected_min": min_files,
    }


def _validate_command(v: Validator, variables: dict[str, str], cwd: Path) -> dict[str, Any]:
    """Run a shell command and check exit code == 0."""
    command = render(v.params.get("run", ""), variables)
    timeout = v.params.get("timeout", 60)
    if not command:
        return {"type": "command", "passed": False, "error": "No command specified"}

    result = subprocess.run(
        ["bash", "-c", command],
        capture_output=True, text=True, cwd=str(cwd), timeout=timeout,
    )
    return {
        "type": "command",
        "passed": result.returncode == 0,
        "command": command,
        "exit_code": result.returncode,
        "stderr": result.stderr[:500] if result.stderr else "",
    }


def _validate_file_exists(v: Validator, variables: dict[str, str], cwd: Path) -> dict[str, Any]:
    """Check that a file or glob pattern matches at least one file."""
    pattern = render(v.params.get("path", ""), variables)
    if not pattern:
        return {"type": "file_exists", "passed": False, "error": "No path specified"}

    # Try as literal path first
    full_path = cwd / pattern
    if full_path.exists():
        return {"type": "file_exists", "passed": True, "path": str(full_path)}

    # Try as glob
    matches = glob_mod.glob(str(cwd / pattern))
    return {
        "type": "file_exists",
        "passed": len(matches) > 0,
        "pattern": pattern,
        "matches": len(matches),
    }


VALIDATORS = {
    "git_diff_check": _validate_git_diff,
    "command": _validate_command,
    "file_exists": _validate_file_exists,
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _resolve_cwd(runner_config: dict[str, Any], variables: dict[str, str]) -> Path:
    """Resolve the working directory from runner_config or default to cwd."""
    cwd_raw = runner_config.get("cwd", "")
    if cwd_raw:
        return Path(render(cwd_raw, variables))
    return Path.cwd()


def _subprocess_run(
    block_id: str,
    cmd: list[str],
    *,
    cwd: Path,
    timeout: int,
) -> BlockResult:
    """Run a subprocess with streaming output and heartbeat watchdog.

    Instead of blocking on subprocess.run, this uses Popen to read stdout
    line-by-line. If no output is received for HEARTBEAT_TIMEOUT_SECONDS,
    the process is killed (prevents "fake death" in CI environments like GHA).
    """
    try:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=str(cwd),
        )
    except FileNotFoundError as exc:
        return BlockResult(
            block_id=block_id,
            success=False,
            stderr=f"Command not found: {exc}",
        )

    stdout_lines: list[str] = []
    stderr_content = ""
    start_time = time.monotonic()
    last_output_time = start_time
    heartbeat_limit = min(HEARTBEAT_TIMEOUT_SECONDS, timeout)

    try:
        # Read stdout line-by-line for heartbeat detection
        assert proc.stdout is not None
        while True:
            # Check overall timeout
            elapsed = time.monotonic() - start_time
            if elapsed > timeout:
                proc.kill()
                proc.wait()
                stderr_content = _drain_stderr(proc)
                return BlockResult(
                    block_id=block_id,
                    success=False,
                    stdout="".join(stdout_lines),
                    stderr=f"Timeout after {timeout}s\n{stderr_content}",
                )

            # Check heartbeat (no output for too long)
            silence = time.monotonic() - last_output_time
            if silence > heartbeat_limit:
                proc.kill()
                proc.wait()
                stderr_content = _drain_stderr(proc)
                return BlockResult(
                    block_id=block_id,
                    success=False,
                    stdout="".join(stdout_lines),
                    stderr=f"Heartbeat timeout: no output for {heartbeat_limit}s\n{stderr_content}",
                )

            # Non-blocking line read via poll + readline
            if proc.poll() is not None:
                # Process exited — drain remaining output
                remaining = proc.stdout.read()
                if remaining:
                    stdout_lines.append(remaining)
                break

            line = proc.stdout.readline()
            if line:
                stdout_lines.append(line)
                last_output_time = time.monotonic()
            else:
                # No data yet, short sleep to avoid busy-wait
                time.sleep(0.1)

        stderr_content = _drain_stderr(proc)
        return BlockResult(
            block_id=block_id,
            success=proc.returncode == 0,
            exit_code=proc.returncode,
            stdout="".join(stdout_lines),
            stderr=stderr_content,
        )

    except Exception as exc:
        proc.kill()
        proc.wait()
        return BlockResult(
            block_id=block_id,
            success=False,
            stderr=f"Unexpected error: {exc}",
        )


def _drain_stderr(proc: subprocess.Popen[str]) -> str:
    """Read all remaining stderr from a finished/killed process."""
    if proc.stderr:
        try:
            return proc.stderr.read()
        except Exception:
            return ""
    return ""
