"""Agentic executor — single Claude CLI call to complete a Blueprint.

Replaces the block-by-block execution engine with one autonomous invocation.
Post-execution validators serve as a quality gate.
"""

from __future__ import annotations

import re
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from kevin.blueprint_compiler import SemanticBlueprint
from kevin.subprocess_utils import run_with_heartbeat


@dataclass
class ExecutorResult:
    """Result of a single agentic execution."""

    success: bool
    exit_code: int | None = None
    stdout: str = ""
    stderr: str = ""
    prompt: str = ""
    duration_seconds: float = 0.0
    validator_results: list[dict[str, Any]] = field(default_factory=list)


def execute(
    compiled_prompt: str,
    *,
    cwd: Path,
    timeout: int,
    model: str = "",
    context_filter: list[str] | None = None,
    dry_run: bool = False,
) -> ExecutorResult:
    """Execute compiled prompt via single `claude -p` call.

    Uses the same heartbeat-monitored subprocess as the block runner.
    """
    if dry_run:
        return ExecutorResult(
            success=True,
            prompt=compiled_prompt,
            stdout=f"[dry-run] Would execute agentic prompt ({len(compiled_prompt)} chars)",
        )

    cmd = [
        "claude", "-p", compiled_prompt,
        "--verbose",
        "--allowedTools", "Read,Write,Edit,Bash,Glob,Grep",
    ]
    if model:
        cmd.extend(["--model", model])

    # Write temporary .claudeignore for context budget management
    claudeignore_path = cwd / ".claudeignore"
    created_claudeignore = False
    if context_filter and not claudeignore_path.exists():
        claudeignore_path.write_text(
            "# Auto-generated by Kevin (context budget management)\n"
            + "\n".join(context_filter)
            + "\n",
            encoding="utf-8",
        )
        created_claudeignore = True

    start = time.monotonic()
    try:
        result = run_with_heartbeat(
            cmd,
            cwd=cwd,
            timeout=timeout,
        )
        duration = time.monotonic() - start
        return ExecutorResult(
            success=result.success,
            exit_code=result.exit_code,
            stdout=result.stdout,
            stderr=result.stderr,
            prompt=compiled_prompt,
            duration_seconds=duration,
        )
    finally:
        if created_claudeignore and claudeignore_path.exists():
            claudeignore_path.unlink()


def run_post_validators(
    semantic: SemanticBlueprint,
    variables: dict[str, str],
    cwd: Path,
) -> list[dict[str, Any]]:
    """Run extracted validators as a post-execution quality gate.

    Reuses validator implementations from agent_runner.
    """
    from kevin.agent_runner import VALIDATORS
    from kevin.blueprint_loader import Validator
    from kevin.prompt_template import render

    # Reconstruct Validator objects from verification_commands
    # Also extract raw validators from the blueprint blocks
    blocks = semantic.raw.get("workflow", {}).get("ralph_loop", {}).get(
        "step_3", {}
    ).get("dependency_graph", {}).get("blocks", [])

    validators: list[Validator] = []
    seen: set[str] = set()

    for block in blocks:
        for v in block.get("validators", []):
            v_type = v.get("type", "")
            # Build a unique key to deduplicate
            key = f"{v_type}:{v.get('path', '')}{v.get('run', '')}"
            if key in seen:
                continue
            seen.add(key)

            params = {k: v2 for k, v2 in v.items() if k != "type"}
            # Render template variables in params
            rendered_params: dict[str, Any] = {}
            for pk, pv in params.items():
                if isinstance(pv, str):
                    rendered_params[pk] = render(pv, variables)
                else:
                    rendered_params[pk] = pv
            validators.append(Validator(type=v_type, params=rendered_params))

    results: list[dict[str, Any]] = []
    for v in validators:
        fn = VALIDATORS.get(v.type)
        if fn is None:
            results.append(
                {"type": v.type, "passed": False, "error": f"Unknown validator: {v.type}"}
            )
            continue
        results.append(fn(v, variables, cwd))

    return results


_PR_URL_PATTERN = re.compile(r"github\.com/[^/]+/[^/]+/pull/(\d+)")
_PR_NUM_PATTERN = re.compile(r"(?:PR\s*#|pull request\s*#?)(\d+)", re.IGNORECASE)


def extract_pr_number(
    stdout: str,
    repo: str = "",
    issue_number: int = 0,
) -> int | None:
    """Extract PR number from executor stdout.

    Strategies (ordered):
    1. Regex for github.com/.../pull/NNN in stdout
    2. Regex for 'PR #NNN' in stdout
    3. Fallback: gh pr list --search 'closes:#N'
    """
    # Strategy 1: GitHub URL
    match = _PR_URL_PATTERN.search(stdout)
    if match:
        return int(match.group(1))

    # Strategy 2: PR #NNN pattern
    match = _PR_NUM_PATTERN.search(stdout)
    if match:
        return int(match.group(1))

    # Strategy 3: gh CLI fallback
    if repo and issue_number:
        return _find_pr_via_gh(repo, issue_number)

    return None


def _find_pr_via_gh(repo: str, issue_number: int) -> int | None:
    """Search for an open PR that closes the given issue."""
    import json

    try:
        result = subprocess.run(
            [
                "gh", "pr", "list",
                "--repo", repo,
                "--state", "open",
                "--search", f"closes:#{issue_number}",
                "--json", "number",
                "--limit", "1",
            ],
            capture_output=True,
            text=True,
            timeout=15,
        )
        prs = json.loads(result.stdout or "[]")
        return prs[0]["number"] if prs else None
    except Exception:
        return None
