"""Agentic executor and post-run helpers for single-worker blueprint runs."""

from __future__ import annotations

import json
import re
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from kevin.agent_runner import _run_validators
from kevin.blueprint_compiler import SemanticBlueprint
from kevin.blueprint_loader import _extract_blocks, _parse_block, _topological_sort
from kevin.subprocess_utils import run_with_heartbeat


@dataclass
class ExecutorResult:
    """Result of a single agentic execution."""

    success: bool
    exit_code: int | None = None
    stdout: str = ""
    stderr: str = ""
    prompt: str = ""
    duration_seconds: float = 0.0
    validator_results: list[dict[str, Any]] = field(default_factory=list)


def execute(
    compiled_prompt: str,
    *,
    cwd: Path,
    timeout: int,
    model: str = "",
    context_filter: list[str] | None = None,
    dry_run: bool = False,
) -> ExecutorResult:
    """Execute compiled prompt via single `claude -p` call."""
    if dry_run:
        return ExecutorResult(
            success=True,
            prompt=compiled_prompt,
            stdout=f"[dry-run] Would execute agentic prompt ({len(compiled_prompt)} chars)",
        )

    cmd = [
        "claude",
        "-p",
        compiled_prompt,
        "--verbose",
        "--allowedTools",
        "Read,Write,Edit,Bash,Glob,Grep",
    ]
    if model:
        cmd.extend(["--model", model])

    claudeignore_path = cwd / ".claudeignore"
    created_claudeignore = False
    if context_filter and not claudeignore_path.exists():
        try:
            claudeignore_path.write_text(
                "# Auto-generated by Kevin (context budget management)\n"
                + "\n".join(context_filter)
                + "\n",
                encoding="utf-8",
            )
            created_claudeignore = True
        except OSError:
            pass  # cwd doesn't exist or not writable — skip context filter

    start = time.monotonic()
    try:
        result = run_with_heartbeat(
            cmd,
            cwd=cwd,
            timeout=timeout,
        )
        duration = time.monotonic() - start
        return ExecutorResult(
            success=result.success,
            exit_code=result.exit_code,
            stdout=result.stdout,
            stderr=result.stderr,
            prompt=compiled_prompt,
            duration_seconds=duration,
        )
    finally:
        if created_claudeignore and claudeignore_path.exists():
            claudeignore_path.unlink()


def run_post_validators(
    semantic: SemanticBlueprint,
    variables: dict[str, str],
    cwd: Path,
) -> list[dict[str, Any]]:
    """Run all block validators from the blueprint after the worker finishes.

    Uses the same validator implementations as block-by-block mode, in dependency order.
    """
    blocks_raw = _extract_blocks(semantic.raw)
    if not blocks_raw:
        return []
    try:
        blocks = [_parse_block(b) for b in blocks_raw]
        ordered = _topological_sort(blocks)
    except Exception as exc:
        return [{"name": "block_parse_error", "passed": False, "error": str(exc)}]
    validators: list = []
    for block in ordered:
        validators.extend(block.validators)
    if not validators:
        return []
    return _run_validators(validators, variables, cwd)


def extract_pr_number(
    stdout: str,
    *,
    repo: str = "",
    issue_number: int = 0,
) -> int | None:
    """Best-effort PR number from worker stdout, then optional gh search."""
    if not stdout:
        return _pr_from_gh_issue(repo, issue_number)

    patterns = [
        r"github\.com/[^/\s]+/[^/\s]+/pull/(\d+)",
        r"https://github\.com/[^/\s]+/[^/\s]+/pull/(\d+)",
        r"\bpull/(\d+)\b",
        r"PR\s*#(\d+)",
        r"pull\s+request\s*#(\d+)",
        r"#(\d+)\s+(?:merged|opened|created)",
    ]
    found: list[int] = []
    for pat in patterns:
        for m in re.finditer(pat, stdout, re.IGNORECASE):
            try:
                found.append(int(m.group(1)))
            except (ValueError, IndexError):
                continue
    if found:
        return found[-1]

    return _pr_from_gh_issue(repo, issue_number)


def _pr_from_gh_issue(repo: str, issue_number: int) -> int | None:
    if not repo or issue_number <= 0:
        return None
    try:
        result = subprocess.run(
            [
                "gh",
                "pr",
                "list",
                "--repo",
                repo,
                "--state",
                "open",
                "--search",
                f"closes:#{issue_number}",
                "--json",
                "number",
                "--limit",
                "1",
            ],
            capture_output=True,
            text=True,
            timeout=15,
        )
        prs = json.loads(result.stdout or "[]")
        return int(prs[0]["number"]) if prs else None
    except Exception:
        return None
