#!/usr/bin/env python3
"""Generate _shared/blueprints.ts from kevin/config.py — single source of truth.

Usage:
  python scripts/sync_blueprints_ts.py          # write file
  python scripts/sync_blueprints_ts.py --check  # CI mode: exit 1 if out of sync
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from kevin.config import DEFAULT_INTENT_MAP, NON_EXECUTABLE_BLUEPRINTS

TARGET = ROOT / "supabase" / "functions" / "_shared" / "blueprints.ts"

HEADER = '''\
// AUTO-GENERATED by scripts/sync_blueprints_ts.py from kevin/config.py
// Do not edit manually — run: python scripts/sync_blueprints_ts.py

'''


def generate() -> str:
    ids = sorted(
        bp_id for bp_id in set(DEFAULT_INTENT_MAP.values())
        if bp_id not in NON_EXECUTABLE_BLUEPRINTS
    )
    lines = [HEADER]
    lines.append("export const VALID_BLUEPRINTS: ReadonlySet<string> = new Set([")
    for bp_id in ids:
        lines.append(f'  "{bp_id}",')
    lines.append("]);\n")
    lines.append("export const AVAILABLE_BLUEPRINTS: ReadonlyArray<string> = [...VALID_BLUEPRINTS].sort();\n")
    return "\n".join(lines)


def main() -> int:
    content = generate()
    check_mode = "--check" in sys.argv

    if check_mode:
        if not TARGET.exists():
            print(f"FAIL: {TARGET} does not exist")
            return 1
        current = TARGET.read_text()
        if current == content:
            print("OK: blueprints.ts is in sync with config.py")
            return 0
        print(f"FAIL: blueprints.ts is out of sync — run: python scripts/sync_blueprints_ts.py")
        return 1

    TARGET.write_text(content)
    print(f"Written {TARGET} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
